import { Cliente } from "./cliente";

export const CLIENTES: Cliente[] = [
    {
      id: 1,
      nombre: 'Pablo',
      apellido: 'Solis',
      email: 'pablo.solis@example.com',
      createAt: '2023-06-11 17:32:11',
    },
    {
      id: 2,
      nombre: 'Victor',
      apellido: 'Solis',
      email: 'victor.solis@example.com',
      createAt: '2023-06-11 17:32:12',
    },
    {
      id: 3,
      nombre: 'Carlos',
      apellido: 'Rodriguez',
      email: 'carlos.rodriguez@example.com',
      createAt: '2023-06-11 17:32:13',
    },
    {
      id: 4,
      nombre: 'Brandon',
      apellido: 'Rodriguez',
      email: 'brandon.rodriguez@example.com',
      createAt: '2023-06-11 17:32:14',
    },
    {
      id: 5,
      nombre: 'Benjamin',
      apellido: 'Aguilera',
      email: 'benjamin.aguilera@example.com',
      createAt: '2023-06-11 17:32:15',
    },
    {
      id: 6,
      nombre: 'Yolanda',
      apellido: 'Sierra',
      email: 'yolanda.sierra@example.com',
      createAt: '2023-06-11 17:32:16',
    },
    {
      id: 7,
      nombre: 'Leslie',
      apellido: 'Issa',
      email: 'leslie.issa@example.com',
      createAt: '2023-06-11 17:32:17',
    },
    {
      id: 8,
      nombre: 'Angela',
      apellido: 'Alvarez',
      email: 'angela.alvarez@example.com',
      createAt: '2023-06-11 17:32:18',
    },
    {
      id: 9,
      nombre: 'Diego',
      apellido: 'Trujillo',
      email: 'diego.trujillo@example.com',
      createAt: '2023-06-11 17:32:19',
    },
    {
      id: 10,
      nombre: 'Oliver',
      apellido: 'Garza',
      email: 'oliver.garza@example.com',
      createAt: '2023-06-11 17:32:20',
    },
    {
      id: 11,
      nombre: 'Jennifer',
      apellido: 'Flores',
      email: 'jennifer.flores@example.com',
      createAt: '2023-06-11 17:32:21',
    },
  ];